//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopNow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string ShopCode { get; set; }
        public string ShopName { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public int Position { get; set; }
        public string Bannerpath { get; set; }
        public System.DateTime Fromdate { get; set; }
        public System.DateTime Todate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public int Status { get; set; }
        public System.DateTime DateEncoded { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public int Days { get; set; }
        public string BannerName { get; set; }
        public Nullable<int> paymentid { get; set; }
        public Nullable<int> CreditType { get; set; }
        public string MasterProductCode { get; set; }
        public string MasterProductName { get; set; }
    
        public virtual Payment Payment { get; set; }
    }
}
