//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopNow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallRecord
    {
        public int Id { get; set; }
        public string Caller { get; set; }
        public string Receiver { get; set; }
        public string CallDuration { get; set; }
        public string RecordId { get; set; }
        public System.DateTime CallDate { get; set; }
        public int OrderNumber { get; set; }
        public string CallId { get; set; }
        public int CallType { get; set; }
        public string StatusText { get; set; }
        public int Status { get; set; }
    }
}
