//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopNow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string ShopCode { get; set; }
        public string ShopName { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string BrandCode { get; set; }
        public string BrandName { get; set; }
        public string CategoryCode { get; set; }
        public string CategoryName { get; set; }
        public string DeliveryAddress { get; set; }
        public string ImagePath { get; set; }
        public string UserEnquiryCode { get; set; }
        public string UserEnquiryName { get; set; }
        public string Qty { get; set; }
        public double Price { get; set; }
        public int CartStatus { get; set; }
        public int Status { get; set; }
        public System.DateTime DateEncoded { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public string CreatedBy { get; set; }
        public string PhoneNumber { get; set; }
        public string OrderNo { get; set; }
        public string DeliveryBoyCode { get; set; }
        public string DeliveryBoyName { get; set; }
        public string DeliveryBoyPhoneNumber { get; set; }
        public double UpdatedPrice { get; set; }
        public double SinglePrice { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public int ShopPaymentStatus { get; set; }
        public int DeliveryBoyPaymentStatus { get; set; }
        public int DeliveryOrderPaymentStatus { get; set; }
        public string UpdatedQty { get; set; }
        public int isUpdate { get; set; }
        public int isDelete { get; set; }
        public int isPriority { get; set; }
        public Nullable<double> Rateperorder { get; set; }
    }
}
