//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopNow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerGiftCard
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string CustomerPhoneNumber { get; set; }
        public string ChannelPartnerNumber { get; set; }
        public string ReferenceCode { get; set; }
        public string GiftCardCode { get; set; }
        public double Amount { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public int Status { get; set; }
        public System.DateTime DateEncoded { get; set; }
        public string CreatedBy { get; set; }
    }
}
