//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopNow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int OwnerType { get; set; }
        public string OfferCode { get; set; }
        public int DiscountType { get; set; }
        public int Type { get; set; }
        public double Percentage { get; set; }
        public int QuantityLimit { get; set; }
        public int AmountLimit { get; set; }
        public int CustomerCountLimit { get; set; }
        public double MinimumPurchaseAmount { get; set; }
        public bool IsForFirstOrder { get; set; }
        public bool IsForOnlinePayment { get; set; }
        public bool IsForBlackListAbusers { get; set; }
        public Nullable<int> BrandId { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> DateEncoded { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    }
}
