//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopNow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public int Customerid { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhonenumber { get; set; }
        public int Shopid { get; set; }
        public string Shopname { get; set; }
        public string DeliveryAddress { get; set; }
        public string ShopPhonenumber { get; set; }
        public string ShopOwnerPhonenumber { get; set; }
        public int TotalProduct { get; set; }
        public int TotalQuantity { get; set; }
        public double TotalPrice { get; set; }
        public int OrderNumber { get; set; }
        public int DeliveryBoyId { get; set; }
        public string DeliverBoyName { get; set; }
        public string DeliveryBoyPhoneNumber { get; set; }
        public double DeliveryCharge { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public int ShopPaymentStatus { get; set; }
        public int DeliveryBoyPaymentStatus { get; set; }
        public int DeliveryOrderPaymentStatus { get; set; }
        public double RatePerOrder { get; set; }
        public int Status { get; set; }
        public System.DateTime DateEncoded { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual DeliveryBoy DeliveryBoy { get; set; }
    }
}
