//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopNow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class paymentsData
    {
        public long id { get; set; }
        public string paymentId { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public string entity { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string currency { get; set; }
        public Nullable<int> status { get; set; }
        public string order_id { get; set; }
        public string invoice_id { get; set; }
        public string method { get; set; }
        public Nullable<decimal> fee { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<System.DateTime> DateEncoded { get; set; }
    }
}
