//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopNow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.Banners = new HashSet<Banner>();
        }
    
        public long Id { get; set; }
        public string CorporateID { get; set; }
        public double Amount { get; set; }
        public string PaymentMode { get; set; }
        public string Key { get; set; }
        public string ReferenceCode { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> ShopId { get; set; }
        public string ShopName { get; set; }
        public string GSTINNumber { get; set; }
        public double OriginalAmount { get; set; }
        public double GSTAmount { get; set; }
        public string Currency { get; set; }
        public string CountryName { get; set; }
        public string PaymentResult { get; set; }
        public string Credits { get; set; }
        public int OrderNumber { get; set; }
        public int PaymentCategoryType { get; set; }
        public int CreditType { get; set; }
        public double ConvenientCharge { get; set; }
        public double PackingCharge { get; set; }
        public double DeliveryCharge { get; set; }
        public double UpdatedAmount { get; set; }
        public double UpdatedOriginalAmount { get; set; }
        public Nullable<double> RefundAmount { get; set; }
        public Nullable<double> RatePerOrder { get; set; }
        public string RefundRemark { get; set; }
        public int RefundStatus { get; set; }
        public int Status { get; set; }
        public string UpdatedBy { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime DateEncoded { get; set; }
        public System.DateTime DateUpdated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Banner> Banners { get; set; }
    }
}
