//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopNow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShopName { get; set; }
        public int ShopCategoryId { get; set; }
        public string ShopCategoryName { get; set; }
        public string GTIN { get; set; }
        public string UPC { get; set; }
        public string GTIN14 { get; set; }
        public string EAN { get; set; }
        public string ISBN { get; set; }
        public double Price { get; set; }
        public int Qty { get; set; }
        public string TypeName { get; set; }
        public int TypeId { get; set; }
        public int MinSelectionLimit { get; set; }
        public int MaxSelectionLimit { get; set; }
        public bool Customisation { get; set; }
        public double MenuPrice { get; set; }
        public int IBarU { get; set; }
        public int ItemId { get; set; }
        public double Percentage { get; set; }
        public int DiscountCategoryId { get; set; }
        public string DiscountCategoryName { get; set; }
        public double DiscountCategoryPercentage { get; set; }
        public int DataEntry { get; set; }
        public int AppliesOnline { get; set; }
        public int DiscountType { get; set; }
        public int DiscountCategoryType { get; set; }
        public bool IsOnline { get; set; }
        public int ShopId { get; set; }
        public int MasterProductId { get; set; }
        public int HoldOnStok { get; set; }
        public int PackingType { get; set; }
        public double TaxPercentage { get; set; }
        public double SpecialCostOfDelivery { get; set; }
        public int OutletId { get; set; }
        public string CategoryNameMain { get; set; }
        public string ItemTimeStamp { get; set; }
        public double LoyaltyPoints { get; set; }
        public double PackingCharge { get; set; }
        public int Status { get; set; }
        public System.DateTime DateEncoded { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
