//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopNow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderItems = new HashSet<OrderItem>();
            this.ProductMedicalStocks = new HashSet<ProductMedicalStock>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string ShopCode { get; set; }
        public string ShopName { get; set; }
        public string CategoryCode { get; set; }
        public string CategoryName { get; set; }
        public string BrandCode { get; set; }
        public string BrandName { get; set; }
        public string ShopCategoryCode { get; set; }
        public string ShopCategoryName { get; set; }
        public string MainSNCode { get; set; }
        public string GTIN { get; set; }
        public string UPC { get; set; }
        public string GTIN12 { get; set; }
        public string GTIN13 { get; set; }
        public string GTIN14 { get; set; }
        public string EAN { get; set; }
        public string ISBN { get; set; }
        public string ImagePath { get; set; }
        public double Price { get; set; }
        public int Qty { get; set; }
        public int Status { get; set; }
        public System.DateTime DateEncoded { get; set; }
        public string MasterProductCode { get; set; }
        public string MasterProductName { get; set; }
        public string ProductType { get; set; }
        public string ColorCode { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string Specification { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public int MinSelectionLimit { get; set; }
        public int MaxSelectionLimit { get; set; }
        public bool Customisation { get; set; }
        public double MenuPrice { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public double weight { get; set; }
        public string SizeLB { get; set; }
        public string MeasurementUnitCode { get; set; }
        public string MeasurementUnitName { get; set; }
        public bool PriscriptionCategory { get; set; }
        public string DrugCompoundDetailCode { get; set; }
        public string CombinationDrugCompound { get; set; }
        public string iBarU { get; set; }
        public string Manufacturer { get; set; }
        public string OriginCountry { get; set; }
        public string ItemId { get; set; }
        public int Percentage { get; set; }
        public string DiscountCategoryCode { get; set; }
        public string DiscountCategoryName { get; set; }
        public double DiscountCategoryPercentage { get; set; }
        public int DataEntry { get; set; }
        public string GoogleTaxonomyCode { get; set; }
        public int AppliesOnline { get; set; }
        public int DiscountType { get; set; }
        public int DiscountCategoryType { get; set; }
        public string PackageCode { get; set; }
        public string PackageName { get; set; }
        public string ImagePathLarge1 { get; set; }
        public string ImagePathLarge2 { get; set; }
        public string ImagePathLarge3 { get; set; }
        public string ImagePathLarge4 { get; set; }
        public string ImagePathLarge5 { get; set; }
        public Nullable<bool> isOnline { get; set; }
        public Nullable<int> shopid { get; set; }
        public Nullable<int> MasterProductId { get; set; }
        public Nullable<int> HoldOnStok { get; set; }
        public Nullable<int> PackagingType { get; set; }
        public Nullable<double> PackagingCharge { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductMedicalStock> ProductMedicalStocks { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
