//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopNow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefundsData
    {
        public long Id { get; set; }
        public string RefundId { get; set; }
        public string Entity { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Currency { get; set; }
        public string Payment_Id { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public Nullable<System.DateTime> DateEncoded { get; set; }
    }
}
