//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopNow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class refundsData
    {
        public long id { get; set; }
        public string refundid { get; set; }
        public string enity { get; set; }
        public Nullable<double> amount { get; set; }
        public string currency { get; set; }
        public string payment_id { get; set; }
        public Nullable<int> orderNo { get; set; }
        public Nullable<System.DateTime> DateEncoded { get; set; }
    }
}
