//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopNow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopDishAddOn
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string AddOnItemName { get; set; }
        public string MasterProductCode { get; set; }
        public string MasterProductName { get; set; }
        public string AddOnCategoryCode { get; set; }
        public string AddOnCategoryName { get; set; }
        public string CrustName { get; set; }
        public int Status { get; set; }
        public System.DateTime DateEncoded { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string PortionCode { get; set; }
        public string PortionName { get; set; }
        public int MinSelectionLimit { get; set; }
        public int MaxSelectionLimit { get; set; }
        public double PortionPrice { get; set; }
        public double AddOnsPrice { get; set; }
        public double CrustPrice { get; set; }
        public int AddOnType { get; set; }
        public Nullable<int> MasterProductId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Shopid { get; set; }
        public string ShopName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int ProductDishAddonId { get; set; }
    }
}
