//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopNow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopMember
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string ShopCode { get; set; }
        public string ShopName { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string MemeberType { get; set; }
        public string TopUpCode { get; set; }
        public int TopUp { get; set; }
        public double RechargeAmount { get; set; }
        public double AvailableAmount { get; set; }
        public System.DateTime RechargeDate { get; set; }
        public System.DateTime ValidateDate { get; set; }
        public int Status { get; set; }
        public System.DateTime DateEncoded { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public string CreatedBy { get; set; }
    }
}
